#!/usr/bin/env bash
if [ -f "env.sh" ]; then
    source env.sh;
fi
if [ -f ".env.sh" ]; then
    source .env.sh;
fi
if [ -z "${PROJECT_DOCKER_REGISTRY_HOST_AND_PORT}" ]; then
    PROJECT_DOCKER_REGISTRY_HOST_AND_PORT=${PROJECT_DOCKER_REGISTRY_HOST:+$PROJECT_DOCKER_REGISTRY_HOST}${PROJECT_DOCKER_REGISTRY_PORT:+":$PROJECT_DOCKER_REGISTRY_PORT"}
fi
if [ -z "${PROJECT_DOCKER_FULL_PATH}" ]; then
    PROJECT_DOCKER_FULL_PATH=${PROJECT_DOCKER_REGISTRY_HOST_AND_PORT:+"$PROJECT_DOCKER_REGISTRY_HOST_AND_PORT/"}${PROJECT_DOCKER_REPOSITORY}${PROJECT_DOCKER_TAG:+":$PROJECT_DOCKER_TAG"}
fi